baseURL: https://chacco38.github.io/
title: クラウドCoEの何でも屋
languageCode: ja-jp
paginate: 5
theme: PaperMod
copyright: "&copy; 2022 Satoshi Matsuzawa"
#googleAnalytics: ""

menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 10
#    - identifier: docs
#      name: Docs
#      url: /docs/
#      weight: 20
#    - identifier: labs
#      name: Labs
#      url: /labs/
#      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 80
    - identifier: search
      name: Search
      url: /search/
      weight: 90

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true

  profileMode:
    enabled: true
    subtitle: "真っ赤なスポーツカーとロックミュージックが好きなITエンジニアの技術ブログ"
    imageUrl: "images/profile.jpeg"

  socialIcons:
    - name: github
      url: https://github.com/chacco38
    - name: twitter
      url: https://twitter.com/chacco38
    - name: facebook
      url: https://www.facebook.com/satoshi.matsuzawa.9
    - name: linkedin
      url: https://www.linkedin.com/in/satoshi-matsuzawa-b209a1157

  editPost:
    URL: "https://github.com/chacco38/chacco38.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  comments: true

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
