baseURL: https://chacco38.github.io/
title: クラウドCoEの何でも屋
languageCode: ja-jp
paginate: 5
theme: PaperMod
copyright: "&copy; 2022 Satoshi Matsuzawa"
# googleAnalytics: ""

menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  author: "Satoshi Matsuzawa"

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true

  profileMode:
    enabled: true
    imageUrl: "images/profile.jpeg"

  socialIcons:
    - name: github
      url: https://github.com/chacco38
    - name: twitter
      url: https://twitter.com/chacco38
    - name: facebook
      url: https://www.facebook.com/satoshi.matsuzawa.9
    - name: linkedin
      url: https://www.linkedin.com/in/satoshi-matsuzawa-b209a1157

        #  editPost:
        #URL: "https://github.com/chacco38/chacco38.github.io/content"
        #Text: "Suggest Changes"
        #appendFilePath: true
